# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
        artifacts:
          - $BITBUCKET_CLONE_DIR DIR/**          
    - step:
        name: Deploy to Test
        deployment: test
        script:
          - echo "Deploying to test environment"
    - step:
        name: Deploy to Production
        deployment: production
        trigger: manual
        script:
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: 'ubuntu'
              SERVER: '35.157.125.215'
              REMOTE_PATH: '/var/www'
              LOCAL_PATH: '*'
          - pipe: atlassian/ssh-run:0.1.4
            variables:
              SSH_USER: 'ubuntu'
              SERVER: '35.157.125.215'
              COMMAND: 'cd /var/www && sudo pm2 start process.yml'
          